### ISSUE TITLE
Workflows documentation misses transitions definitions

### ISSUE THREAD

**Issue by moritz-votum** [oroinc/documentation#228]
The doc on workflows (https://www.orocrm.com/documentation/index/current/reference/format/workflows) omits transition definitions leaving the reader just with the information that this is a map.

**Comment by mkudelya** [comment]
Hi @moritz-votum 

We will consider your wishes, thank you for the suggestions!

**Comment by anyt** [comment]
Closed. Transitions definitions are documented here: https://doc.oroinc.com/backend/entities-data-management/workflows/configuration-reference/#transition-definition-configuration.
Thank you!
