### ISSUE TITLE
Install Documentation Inconsistencies

### ISSUE THREAD

**Issue by aligentjim** [oroinc/documentation#230]
Working through our first OroCRM builds, I found the instructions in the Oro Book very comprehensive and useful.  However, when comparing the installation instructions in the Book to the README in the application repo, there's a couple of inconsistences which as a new comer to the platform I found confusing.

1. The README documents that a Clank server for websockets needs to be running <https://github.com/orocrm/crm-application/blame/1.10/README.md#L58> but this isn't mentioned in the book.  I assume running this process under `supervisord` or similar is recommended, but some documention around the recommended way to run it, configuration, etc would be great.  Information on how to test the websocket server and what breaks if it's not running (OroCRM seems fine without it?) to assist with troubeshooting would also be helpful.

1. The README mentions that a cron job needs to be scheduled <https://github.com/orocrm/crm-application/blame/1.10/README.md#L67> but this isn't described in the book.  Seems like an obvious requirement for a modern web app, and I'm sure most people are familiar with cron but mentioning it in the book would be helpful.

There may be other issues around different PHP extensions/versions, etc as well, but these two seem like a couple of major application pieces which were omitted from the book entirely.

**Comment by xabbuh** [comment]
For your interest and if you want to dig a bit deeper: The cron job configuration part is covered in the [job execution chapter](https://www.orocrm.com/documentation/index/current/book/jobs).

**Comment by aligentjim** [comment]
The cron documentation in the job execution chapter is great (all the oro documentation is great actually), but as a newbie to the platform it would be good if either the installation document included the cron stuff directly, or linked to is in a "Next Steps" section at the end.  I'd ideally like to not have to read the entire book to know that I've got Oro completely installed.  I have no doubt I'll read the entire book eventually, but not today :)

**Comment by mkudelya** [comment]
Hi @aligentjim 

[Installation](https://www.orocrm.com/documentation/index/current/book/installation) chapter of book already contains "Activating Background Tasks" topic.
We will add "clank server" topic to our book, thank you!

**Comment by aligentjim** [comment]
Thanks!

**Comment by anyt** [comment]
It is closed as the documentation has been refactored from scratch. It already includes cron and WebSocket configuration reference: https://doc.oroinc.com/backend/setup/installation/. 
Thank you!
