### ISSUE TITLE
Propose to add (or at least to mention) the «--timeout» key in the «5b. Using the Installation Command», because the default timeout of 300 seconds is often too small and could break the installation

### ISSUE THREAD

**Issue by dmitry-fedyuk** [oroinc/documentation#237]
https://github.com/orocrm/documentation/blob/temp2.0/book/installation.rst#5b-using-the-installation-command
![14](https://cloud.githubusercontent.com/assets/83204/26184200/23760240-3b8c-11e7-8d92-ffe9d44b6b14.png)

**Comment by mkudelya** [comment]
Hi @dmitry-fedyuk 

Thank you for pointing out the issue.

**Comment by anyt** [comment]
Closed. Timeout is already documented: https://doc.oroinc.com/backend/setup/installation/#install-oro-application.
Thank you!
