### ISSUE TITLE
Web API: config

### ISSUE THREAD

**Issue by AntseN** [oroinc/documentation#247]
Hello the documentation states that we can config some api options in the config.yml file (https://doc.oroinc.com/api/authentication/oauth-client-credentials/) 

> expires_in = 3600 seconds. Once the token is generated, it is valid for an hour and can be used multiple times within this time limit to request the necessary data. Expiration time can by configured in config.yml.

But we have no indication of what to set up in the config.yml. I would like to change the token's expiration date, but i don't know how...., what other parameters can we change ? where ? how ?

**Comment by anyt** [comment]
in config.yml it can be configured like this:
```
oro_oauth2_server:
   authorization_server:
        access_token_lifetime: 3600
```
